---
- name: install/upgrade mako
  package:
    state: latest
    name: mako

- name: copy mako config
  copy:
    src: "{{ role_path }}/files/files"
    dest: "{{ user_home_dir }}/.config/mako/config"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
