---
- name: install dependencies
  become: yes
  dnf:
    name:
      - libdrm
      - libX11-xcb
      - libxshmfence
      - mesa-libgbm
      - which
    state: present

- name: install VS Code repo
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code repo
    file: vscode
    baseurl: '{{ visual_studio_code_mirror }}/yumrepos/vscode'
    gpgkey: '{{ visual_studio_code_mirror }}/keys/microsoft.asc'
    gpgcheck: yes

- name: install VS Code
  become: yes
  dnf:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('-' + visual_studio_code_version, '') }}"
    state: present
