---
- name: install/upgrade git
  package:
    state: latest
    name: git

- name: push git user config files
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_home_dir }}/.{{ item }}"
    mode: 0600
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    seuser: system_u
  loop:
    - gitconfig
    - gitconfig-unicef
