---
- name: create preferred path for RPM packaging
  file:
    path: "{{ user_home_dir }}/git/fedora/rpms/"
    state: directory
    group: "{{ target_group }}"
    owner: "{{ target_user }}"

- name: install Fedora packaging tools
  package:
    state: present
    name:
      - copr-cli
      - fedpkg
      - fedora-packager
      - fedora-review
      - mock
      - qemu-user-static

- name: add target user to mock group
  user:
    name: "{{ target_user }}"
    groups: mock
    append: yes
