---
- name: install i3wm
  package:
    state: present
    name:
      - i3
      - i3lock

- name: create i3wm user config directory
  file:
    state: directory
    path: "{{ user_home_dir }}/.config/i3"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"

- name: add i3wm user config files
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_home_dir }}/.config/i3/{{ item }}"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
  loop:
    - config
    - i3status.conf

- name: add i3wm user scripts
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ user_home_dir }}/.config/i3/{{ item }}"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
    mode: 0775
  loop:
    - fuzzy_lock.sh
    - i3exit.sh
