---
- name: install/upgrade tmux
  package:
    state: latest
    name: tmux

- name: copy tmux.conf
  copy:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ user_home_dir }}/.tmux.conf"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"

- name: copy tmux.conf.local
  copy:
    src: "{{ role_path }}/files/tmux.conf.local"
    dest: "{{ user_home_dir }}/.tmux.conf.local"
    group: "{{ target_user }}"
    owner: "{{ target_user }}"
