---
- name: download and extract Minecraft launcher
  unarchive:
    creates: "/usr/local/games/minecraft-launcher/"
    dest: "/usr/local/games/"
    remote_src: yes
    src: https://launcher.mojang.com/download/Minecraft.tar.gz

- name: install desktop file
  copy:
    src: "{{ role_path }}/files/minecraft.desktop"
    dest: "/usr/local/share/applications/minecraft.desktop"
