---
- name: synchronize Justin's preferred environment for jflory7.fedorapeople.org
  hosts: fedorapeople

  vars:
    target_group: jflory7
    target_user: jflory7
    target_user_name: Justin W. Flory
    user_home_dir: /home/fedora/jflory7

  roles:
    - { role: apps/bash, tags: ['bash', 'terminal', 'apps'] }
    - { role: apps/git, tags: ['git', 'terminal', 'apps'] }
    - { role: apps/vim, tags: ['vim', 'terminal', 'apps'] }
